// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The `bool` encrypted-domain family — generated from the eql-domains catalog.
use crate::v3::terms::Ciphertext;
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `eql_v3.bool` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Bool {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Bool {
    fn sql_domain_static() -> &'static str {
        "eql_v3.bool"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Bool)
    }
}
