// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The `float8` encrypted-domain family — generated from the eql-domains catalog.
use crate::v3::terms::{Ciphertext, Hmac256, OreBlock256};
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `eql_v3.float8` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float8 {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Float8 {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float8"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float8)
    }
}
/// `eql_v3.float8_eq` — equality domain.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `c` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float8Eq {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub hm: Hmac256,
}
impl DomainType for Float8Eq {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float8_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float8Eq)
    }
}
/// `eql_v3.float8_ord_ore` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float8OrdOre {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for Float8OrdOre {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float8_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float8OrdOre)
    }
}
/// `eql_v3.float8_ord` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float8Ord {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for Float8Ord {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float8_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float8Ord)
    }
}
