// @generated by eql-codegen from the eql-domains catalog — do not edit
//! The `float4` encrypted-domain family — generated from the eql-domains catalog.
use crate::v3::terms::{Ciphertext, Hmac256, OreBlock256};
use crate::v3::DomainType;
use crate::{Identifier, SchemaVersion};
use schemars::{schema_for, JsonSchema, Schema};
use serde::{Deserialize, Serialize};
use ts_rs::TS;
/// `eql_v3.float4` — storage-only domain.
///
/// Operators: none. Required keys: `v` `i` `c`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float4 {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
}
impl DomainType for Float4 {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float4"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float4)
    }
}
/// `eql_v3.float4_eq` — equality domain.
///
/// Operators: `=` `<>`. Required keys: `v` `i` `c` `hm`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float4Eq {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub hm: Hmac256,
}
impl DomainType for Float4Eq {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float4_eq"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float4Eq)
    }
}
/// `eql_v3.float4_ord_ore` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float4OrdOre {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for Float4OrdOre {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float4_ord_ore"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float4OrdOre)
    }
}
/// `eql_v3.float4_ord` — ordering domain.
///
/// Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `c` `ob`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[ts(export, export_to = "v3/")]
#[serde(deny_unknown_fields)]
pub struct Float4Ord {
    pub v: SchemaVersion,
    pub i: Identifier,
    pub c: Ciphertext,
    pub ob: OreBlock256,
}
impl DomainType for Float4Ord {
    fn sql_domain_static() -> &'static str {
        "eql_v3.float4_ord"
    }
    fn sql_domain(&self) -> &'static str {
        Self::sql_domain_static()
    }
    fn schema(&self) -> Schema {
        schema_for!(Float4Ord)
    }
}
