[package]
name = "eql-test"
version = "0.1.0"
edition = "2021"

[dependencies]
eql-core = { path = "../eql-core" }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
serde_json = { workspace = true }
