name: eql
services:
  cipherstash-proxy:
    container_name: eql-cipherstash-proxy
    ports:
      - 6432:6432
    environment:
      - CS_STATEMENT_HANDLER=mylittleproxy
      - LOG_LEVEL=debug
    volumes:
      - ./cipherstash-proxy.toml:/etc/cipherstash-proxy/cipherstash-proxy.toml
    image: cipherstash/cipherstash-proxy:cipherstash-proxy-v0.1.1
