// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

/**
 * Scalar storage payload (`k = "ct"`).
 *
 * FROZEN imperfection: `hm`/`bf`/`ob` are independently optional. A consumer
 * cannot tell from the type which terms are present — it must inspect at
 * runtime. This is precisely the gap the `protect-dynamodb` bug fell into.
 * The fix, for *new* types, is [`crate::int4`].
 */
export type EncryptedPayload = { 
/**
 * Schema version — always [`crate::EQL_SCHEMA_VERSION`].
 */
v: number, 
/**
 * Table/column identifier.
 */
i: Identifier, 
/**
 * mp_base85 ciphertext. Required.
 */
c: string, 
/**
 * HMAC-SHA256 equality term — present iff a `unique` index is configured.
 */
hm?: string, 
/**
 * Bloom filter term — present iff a `match` index is configured.
 */
bf?: Array<number>, 
/**
 * Block ORE term — present iff an `ore` index is configured.
 */
ob?: Array<string>, };
