// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedPayload } from "./EncryptedPayload";
import type { SteVecPayload } from "./SteVecPayload";

/**
 * `eql_v2_encrypted` — the EQL v2.3 storage payload.
 *
 * **Serialization** always emits the `k` discriminator (`"ct"` / `"sv"`) —
 * this is what drives the internally-tagged TypeScript union and the JSON
 * Schema `oneOf`. **Deserialization** is hand-written (below) because the
 * v2.3 wire contract makes `k` *optional* on the scalar form:
 * `eql_v2.check_encrypted` and `eql-payload-v2.3.schema.json` discriminate on
 * the presence of `c` vs `sv`, not on `k` (the scalar form requires only
 * `v`, `c`, `i`). A `#[serde(tag = "k")]`-derived `Deserialize` would reject a
 * schema-valid scalar payload that omits `k`.
 */
export type EqlEncrypted = { "k": "ct" } & EncryptedPayload | { "k": "sv" } & SteVecPayload;
