// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedPayload } from "./EncryptedPayload";
import type { SteVecPayload } from "./SteVecPayload";

/**
 * `eql_v2_encrypted` — the EQL v2.3 storage payload. Discriminated on `k`.
 */
export type EqlEncrypted = { "k": "ct" } & EncryptedPayload | { "k": "sv" } & SteVecPayload;
