// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

/**
 * `eql_v2_int4_eq` — HMAC equality (`=`, `<>`).
 *
 * `hm` is a required field. There is no `Option`: the type *is* the
 * equality capability. A payload without `hm` cannot be deserialized into
 * this type — the Rust analogue of the SQL domain's CHECK constraint.
 */
export type Int4Eq = { 
/**
 * Schema version.
 */
v: number, 
/**
 * Table/column identifier.
 */
i: Identifier, 
/**
 * mp_base85 ciphertext. Required.
 */
c: string, 
/**
 * HMAC-SHA256 equality term. Required.
 */
hm: string, };
