// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

/**
 * `eql_v2_int4` — storage only. Carries `c`; every operator is blocked.
 */
export type Int4 = { 
/**
 * Schema version.
 */
v: number, 
/**
 * Table/column identifier.
 */
i: Identifier, 
/**
 * mp_base85 ciphertext. Required by the domain's CHECK constraint.
 */
c: string, };
