// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

/**
 * **Proposed.** Self-describing int4 payload — `x` is the capability tag.
 *
 * Generates a clean TypeScript discriminated union (`switch (p.x)` with
 * exhaustiveness) and a JSON Schema `oneOf` with a per-branch `const`.
 */
export type Int4Tagged = { "x": "int4", v: number, i: Identifier, c: string, } | { "x": "int4_eq", v: number, i: Identifier, c: string, hm: string, } | { "x": "int4_ord", v: number, i: Identifier, c: string, ob: Array<string>, };
