// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";

/**
 * `eql_v2_int4_ord` — equality + ORE-block range (`=` `<>` `<` `<=` `>` `>=`).
 *
 * Deliberately carries no `hm`: ORE over a full-domain `int4` is lossless, so
 * the order term `ob` doubles as an exact equality term.
 * (`eql_v2_int4_ord_ore` in #225 is the same shape under a scheme-explicit
 * name — structurally identical, so it is not a separate Rust type.)
 */
export type Int4Ord = { 
/**
 * Schema version.
 */
v: number, 
/**
 * Table/column identifier.
 */
i: Identifier, 
/**
 * mp_base85 ciphertext. Required.
 */
c: string, 
/**
 * Block ORE term. Required — serves both range and equality.
 */
ob: Array<string>, };
