// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One STE-vector element.
 */
export type SteVecElement = { 
/**
 * Tokenized selector — deterministic per (path, key).
 */
s: string, 
/**
 * Per-entry mp_base85 ciphertext. Required.
 */
c: string, 
/**
 * Array marker — true when the selector points at a JSON array context.
 */
a?: boolean, } & ({ hm: string, } | { oc: string, });
