// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { SteVecElement } from "./SteVecElement";

/**
 * STE-vector storage payload (`k = "sv"`).
 */
export type SteVecPayload = { 
/**
 * Schema version.
 */
v: number, 
/**
 * Table/column identifier.
 */
i: Identifier, 
/**
 * Per-selector encrypted entries; root document ciphertext at `sv[0].c`.
 */
sv: Array<SteVecElement>, };
