// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * SteVec element term. FROZEN as **untagged** — this is the v2.3 wire shape.
 *
 * A consumer must narrow with `'hm' in term`; there is no literal
 * discriminant. A *new* type would tag this — see [`crate::int4`].
 */
export type SteVecTerm = { hm: string, } | { oc: string, };
