// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.bool` — storage-only domain.
 *
 * Operators: none. Required keys: `v` `i` `c`.
 */
export type Bool = { v: SchemaVersion, i: Identifier, c: Ciphertext, };
