// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `public.eql_v3_json` — a storage-only / encryption-only encrypted JSON value:
 * a plain `{v, i, c}` envelope (the ciphertext of the whole JSON document) with
 * NO SteVec structure and no index terms. The JSON analogue of the scalar
 * storage domains (`Integer` etc.); supports no eql operators. For a searchable
 * encrypted document use [`SteVecDocument`] (`public.eql_v3_json_search`).
 * Strict. Hand-written (like the SteVec structs) but shaped exactly like a
 * generated scalar storage struct — its catalog domain is `Shape::Scalar`.
 * CIP-3512.
 */
export type Json = { v: SchemaVersion, i: Identifier, c: Ciphertext, };
