// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { OpeCllw } from "./OpeCllw";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `public.smallint_ord_ope_query` — ordering domain query operand.
 *
 * Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
 */
export type SmallintOrdOpeQuery = { v: SchemaVersion, i: Identifier, op: OpeCllw, };
