// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeCllw } from "./OpeCllw";
import type { Selector } from "./Selector";

/**
 * One element of a SteVec containment needle: a selector plus — for ordered
 * path entries only — the `op` ordering term; value-selector and structural
 * entries are selector-only (matched on presence), and (per the SQL CHECK)
 * no element carries a ciphertext. LAX for the same flatten reason as
 * `SteVecEntry`; the "no `c`" contract is enforced by `is_valid_ste_vec_query_payload`.
 */
export type SteVecQueryEntry = { s: Selector, } & ({ op: OpeCllw, } | Record<string, never>);
