// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SteVecQueryEntry } from "./SteVecQueryEntry";

/**
 * `public.jsonb_query` — a containment needle (`{sv:[query-entry]}`). Strict.
 */
export type SteVecQuery = { sv: Array<SteVecQueryEntry>, };
