// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";
import type { SteVecEntry } from "./SteVecEntry";

/**
 * `eql_v3.json` — a SteVec encrypted-JSONB document (`{v, i, sv:[entry]}`, no
 * root ciphertext). Strict.
 */
export type SteVecDocument = { v: SchemaVersion, i: Identifier, sv: Array<SteVecEntry>, };
