// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hmac256 } from "./Hmac256";
import type { Identifier } from "./Identifier";
import type { OreBlock256 } from "./OreBlock256";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `public.text_ord_query` — ordering domain query operand.
 *
 * Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `hm` `ob`.
 */
export type TextOrdQuery = { v: SchemaVersion, i: Identifier, hm: Hmac256, ob: OreBlock256, };
