// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BloomFilter } from "./BloomFilter";
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `public.text_match_query` — match domain query operand.
 *
 * Operators: `@>` `<@`. Required keys: `v` `i` `bf`.
 */
export type TextMatchQuery = { v: SchemaVersion, i: Identifier, bf: BloomFilter, };
