// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BloomFilter } from "./BloomFilter";
import type { Ciphertext } from "./Ciphertext";
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.text_match` — Bloom-filter containment match.
 */
export type TextMatch = { 
/**
 * Envelope version — always `2` (`EQL_SCHEMA_VERSION`); any other
 * value fails deserialization.
 */
v: SchemaVersion, 
/**
 * Table/column identifier. Required by the domain CHECK.
 */
i: Identifier, 
/**
 * mp_base85 source ciphertext. Required by the domain CHECK.
 */
c: Ciphertext, 
/**
 * Bloom-filter match term (signed smallint bit positions).
 */
bf: BloomFilter, };
