//! Per-scalar matrix suites, generated by the `scalar_types!(matrix_suites)`
//! invocation below — one module per scalar type, each holding its
//! `scalar_matrix!` suite.
//!
//! The modules are generated from the single harness list in
//! `tests/sqlx/src/scalar_types.rs` — adding a type there adds its suite here
//! automatically. The old per-type `scalars/<token>.rs` files are gone.

eql_tests::scalar_types!(matrix_suites);
