CREATE SCHEMA IF NOT EXISTS eql_v1;

DROP FUNCTION IF EXISTS eql_v1.version();

CREATE FUNCTION eql_v1.version()
  RETURNS text
  IMMUTABLE STRICT PARALLEL SAFE
AS $$
  SELECT '$RELEASE_VERSION';
$$ LANGUAGE SQL;

