["test:rust"]
description = "Run Rust test framework"
dir = "{{config_root}}/tests/sqlx"
run = """
# Ensure database is running
mise run postgres:up --extra-args "--detach --wait"

# Run tests
cargo test
"""

["test:rust:watch"]
description = "Run Rust tests in watch mode"
dir = "{{config_root}}/tests/sqlx"
run = """
cargo watch -x test
"""
