["test:sqlx"]
description = "Run SQLx tests with hybrid migration approach"
dir = "{{config_root}}"
env = { DATABASE_URL = "postgresql://{{get_env(name='POSTGRES_USER', default='cipherstash')}}:{{get_env(name='POSTGRES_PASSWORD', default='password')}}@{{get_env(name='POSTGRES_HOST', default='localhost')}}:{{get_env(name='POSTGRES_PORT', default='7432')}}/{{get_env(name='POSTGRES_DB', default='cipherstash')}}" }
run = """
# Copy built SQL to SQLx migrations (EQL install is generated, not static)
echo "Updating SQLx migrations with built EQL..."
cp release/cipherstash-encrypt.sql tests/sqlx/migrations/001_install_eql.sql

# Run SQLx migrations and tests
echo "Running SQLx migrations..."
cd tests/sqlx
sqlx migrate run

echo "Running Rust tests..."
cargo test
"""

["test:sqlx:watch"]
description = "Run SQLx tests in watch mode (rebuild EQL on changes)"
dir = "{{config_root}}/tests/sqlx"
run = """
cargo watch -x test
"""
