// AUTO-GENERATED — DO NOT EDIT.
// Regenerated by `mise run build` (or `mise run codegen:domain <type>`).
// Source of truth: tasks/codegen/types/<type>.toml `[fixture] values`.
// This file IS committed and verified in CI (git diff --exit-code).
//! Fixture plaintext values for the int8 encrypted-domain family.
//!
//! Generated from tasks/codegen/types/int8.toml `[fixture] values` —
//! the single source of truth shared by the fixture generator
//! (`fixtures::eql_v2_int8`) and the matrix oracle
//! (`ScalarType::FIXTURE_VALUES`).

/// Distinct plaintext values present in the `eql_v2_int8` fixture.
pub const VALUES: &[i64] = &[
    i64::MIN,
    -5000000000,
    -100,
    -1,
    0,
    1,
    2,
    5,
    10,
    17,
    25,
    42,
    50,
    100,
    250,
    1000,
    9999,
    5000000000,
    i64::MAX,
];
