//! Type-checked fixture generation framework.
//!
//! A fixture is one Rust file under `src/fixtures/` declaring a `FixtureSpec`.
//! `FixtureSpec::run()` generates the SQLx fixture script
//! `tests/sqlx/fixtures/<name>.sql` (gitignored — regenerated on every
//! `mise run test:sqlx`).

pub mod validation;

pub mod eql_plaintext;

pub use eql_plaintext::EqlPlaintext;

pub mod index_kind;

pub use index_kind::IndexKind;

pub mod spec;

pub use spec::FixtureSpec;

#[macro_use]
pub mod scalar_fixture;

pub mod cipherstash;

pub mod driver;

/// Generated from the `int4` row in `eql-scalars::CATALOG` (`fixtures`).
/// Committed and verified by CI; never hand-edit (regenerated by `eql-codegen`).
pub mod int4_values;

pub mod eql_v2_int4;

/// Generated from the `int2` row in `eql-scalars::CATALOG` (`fixtures`).
/// Committed and verified by CI; never hand-edit (regenerated by `eql-codegen`).
pub mod int2_values;

pub mod eql_v2_int2;
