//! The `v3_text_empty` fixture — the empty string `""` plus two non-empty
//! controls, encrypted as ordered text.
//!
//! Hand-written, non-catalog (like `v3_numeric_collision`), because the
//! catalog-driven `eql_v2_text` fixture deliberately EXCLUDES `""`: encrypting
//! the empty string yields an empty ORE term (`ob: []`) whose ordering was
//! undefined (issue #262), so `eql-scalars::TEXT_FIXTURES` drops it. This
//! bespoke fixture is the one place `""` can live, giving the end-to-end
//! "empty sorts first" contract (ORDER BY / min / max) a real-ciphertext home.
//!
//! Rows are addressed by `id` (1-based insertion ordinal): `"" → 1`,
//! `"frank" → 2`, `"zebra" → 3`. The contract under test: `""` sorts BEFORE
//! both non-empty values, so `eql_v3.min` returns the `id = 1` (`""`) payload
//! and `eql_v3.max` returns the `id = 3` (`"zebra"`) payload.
//!
//! Gitignored output: tests/sqlx/fixtures/v3_text_empty.sql
//! (regenerated by `mise run fixture:generate:all`).

use anyhow::Result;

use super::index_kind::IndexKind;
use super::spec::FixtureSpec;

/// The committed fixture name → table `fixtures.v3_text_empty`, script
/// `v3_text_empty.sql`, SQLx ref `scripts("v3_text_empty")`.
const NAME: &str = "v3_text_empty";

/// The fixture plaintexts, in insertion order. `id` is the 1-based ordinal, so
/// `"" → 1`, `"frank" → 2`, `"zebra" → 3`. The empty string is the value with
/// no ORE term; the two non-empty controls prove `min`/`max`/ORDER BY return
/// real values around it (not a degenerate everything-collides).
fn values() -> Vec<String> {
    ["", "frank", "zebra"]
        .iter()
        .map(|s| s.to_string())
        .collect()
}

/// Generate `tests/sqlx/fixtures/v3_text_empty.sql`. Encrypts the three strings
/// as ordered text (Unique drives the `hm` equality term, Ore drives the `ob`
/// order term — empty for `""`) via the standard `.run()` driver.
pub async fn generate() -> Result<()> {
    let values = values();
    FixtureSpec::new(NAME)
        .with_index(IndexKind::Unique)
        .with_index(IndexKind::Ore)
        .with_values(&values)
        .run()
        .await
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_is_first_and_controls_are_ordered() {
        let v = values();
        assert_eq!(v.len(), 3, "fixture is [\"\", \"frank\", \"zebra\"]");
        assert!(v[0].is_empty(), "id 1 must be the empty string");
        assert!(!v[1].is_empty() && !v[2].is_empty(), "controls are non-empty");
        // The controls are strictly ordered so max is unambiguous.
        assert!(v[1] < v[2], "\"frank\" must order before \"zebra\"");
    }
}
