services:
  postgres:
    container_name: cipherstash_getting_started_pg
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cipherstash_getting_started
    ports:
      - ${PGPORT:-5432}:5432
    networks:
      - cipherstash_getting_started_nw
  proxy:
    container_name: cipherstash_getting_started_proxy
    image: cipherstash/cipherstash-proxy:latest
    depends_on:
      - postgres
    ports:
      - ${CS_PORT:-6432}:${CS_PORT:-6432}
    environment:
      CS_WORKSPACE_ID: $CS_WORKSPACE_ID
      CS_CLIENT_ACCESS_KEY: $CS_CLIENT_ACCESS_KEY
      CS_ENCRYPTION__CLIENT_ID: $CS_ENCRYPTION__CLIENT_ID
      CS_ENCRYPTION__CLIENT_KEY: $CS_ENCRYPTION__CLIENT_KEY
      CS_ENCRYPTION__DATASET_ID: $CS_DATASET_ID
      CS_TEST_ON_CHECKOUT: "true"
      CS_AUDIT__ENABLED: "false"
      CS_DATABASE__PORT: 5432
      CS_DATABASE__USERNAME: postgres
      CS_DATABASE__PASSWORD: postgres
      CS_DATABASE__NAME: cipherstash_getting_started
      CS_DATABASE__HOST: cipherstash_getting_started_pg
      CS_UNSAFE_LOGGING: "true"
    networks:
      - cipherstash_getting_started_nw

networks:
  cipherstash_getting_started_nw:
    driver: bridge
