// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bloom-filter match term — the `bf` wire key. Backs the `_match` domains
 * (`~~` containment via `@>`/`<@`).
 *
 * **Signed** i16, not u16: EQL stores the filter as PostgreSQL `smallint[]`,
 * and filters sized above 32768 emit upper-half bit positions as negative
 * signed values (same rationale as `v2_3::EncryptedPayload::bf`).
 */
export type BloomFilter = Array<number>;
