// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Identifier } from "../Identifier";
import type { OreBlockU64_8_256 } from "./OreBlockU64_8_256";

/**
 * `eql_v3.date_ord_ore` — full comparison, scheme-explicit name.
 */
export type DateOrdOre = { 
/**
 * Envelope version — always `2` (`EQL_SCHEMA_VERSION`).
 */
v: number, 
/**
 * Table/column identifier. Required by the domain CHECK.
 */
i: Identifier, 
/**
 * mp_base85 source ciphertext. Required by the domain CHECK.
 */
c: Ciphertext, 
/**
 * Block-ORE order term. Serves equality too.
 */
ob: OreBlockU64_8_256, };
