// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Hmac256 } from "./Hmac256";
import type { Identifier } from "../Identifier";

/**
 * `eql_v3.int8_eq` — HMAC equality (`=`, `<>`).
 */
export type Int8Eq = { 
/**
 * Envelope version — always `2` (`EQL_SCHEMA_VERSION`).
 */
v: number, 
/**
 * Table/column identifier. Required by the domain CHECK.
 */
i: Identifier, 
/**
 * mp_base85 source ciphertext. Required by the domain CHECK.
 */
c: Ciphertext, 
/**
 * HMAC-SHA-256 equality term.
 */
hm: Hmac256, };
