// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Hmac256 } from "./Hmac256";
import type { Identifier } from "./Identifier";
import type { OreBlock256 } from "./OreBlock256";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.text_ord_ore` — full lexicographic comparison,
 * scheme-explicit name. Unlike the integer ordered domains (`[Ore]` only),
 * text routes equality through `hm` rather than the ORE term, so the domain
 * carries both `hm` and `ob` (`[Hm, Ore]`).
 */
export type TextOrdOre = { 
/**
 * Envelope version — always `2` (`EQL_SCHEMA_VERSION`); any other
 * value fails deserialization.
 */
v: SchemaVersion, 
/**
 * Table/column identifier. Required by the domain CHECK.
 */
i: Identifier, 
/**
 * mp_base85 source ciphertext. Required by the domain CHECK.
 */
c: Ciphertext, 
/**
 * HMAC-SHA-256 equality term. Text routes `=`/`<>` through `hm`.
 */
hm: Hmac256, 
/**
 * Block-ORE order term.
 */
ob: OreBlock256, };
