[package]
name = "eql-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
eql-core = { path = "../eql-core" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
eql-test = { path = "../eql-test" }
tokio = { workspace = true }
