//! Fixture-based test suite for `eql_v2_int4_ord_ore` — the
//! HMAC + ORE-block ordering variant.
//!
//! Consumes `tests/sqlx/migrations/009_install_encrypted_int4_fixture.sql`
//! (table `encrypted_int4_plaintext`, column `payload JSONB NOT NULL`),
//! generated by `mise run fixture:int:generate` against real
//! CipherStash Proxy output. Each row pairs a plaintext integer with
//! its encrypted JSONB payload carrying HMAC + ORE block terms.
//!
//! Value set: { -100, -1, 1, 2, 5, 10, 17, 25, 42, 50, 100, 250, 1000, 9999 }
//! 14 rows. Range pivots produce distinct cardinalities so swapped
//! operators would fail the assertions, not silently pass.
//!
//! Tests cast `payload::eql_v2_int4_ord_ore` per-query so the fixture
//! table itself stays JSONB-shaped. Range ordering is asserted via
//! `ORDER BY eql_v2.ore_block_u64_8_256(payload::jsonb)` — sorting on
//! the domain column directly would follow native jsonb comparison.
//!
//! Range queries are seq-scan: compare_ore_block_u64_8_256 is
//! PL/pgSQL and does not inline. No EXPLAIN engagement assertion
//! for range; equality engagement is asserted on the hmac functional
//! btree.

use anyhow::Result;
use sqlx::PgPool;

/// Pull plaintext column out of fixture rows whose payload satisfies a
/// predicate. The predicate is the SQL fragment that goes after `WHERE`.
async fn plaintexts_matching(pool: &PgPool, predicate: &str) -> Result<Vec<i32>> {
    let sql = format!(
        "SELECT plaintext FROM encrypted_int4_plaintext WHERE {predicate} ORDER BY plaintext"
    );
    let mut rows: Vec<i32> = sqlx::query_scalar(&sql).fetch_all(pool).await?;
    rows.sort();
    Ok(rows)
}

#[sqlx::test]
async fn encrypted_int4_equality_matches_self(pool: PgPool) -> Result<()> {
    // For each fixture plaintext, looking up by `=` against that row's own
    // payload must return exactly that plaintext.
    for target in [-100, -1, 1, 42, 9999] {
        let needle: String = sqlx::query_scalar(
            "SELECT payload::text FROM encrypted_int4_plaintext WHERE plaintext = $1",
        )
        .bind(target)
        .fetch_one(&pool)
        .await?;

        let matched: Vec<i32> = plaintexts_matching(
            &pool,
            &format!(
                "payload::eql_v2_int4_ord_ore = '{}'::jsonb::eql_v2_int4_ord_ore",
                needle.replace('\'', "''")
            ),
        )
        .await?;
        assert_eq!(matched, vec![target], "= against payload of {target}");
    }

    Ok(())
}

#[sqlx::test]
async fn encrypted_int4_equality_cross_type_shapes(pool: PgPool) -> Result<()> {
    // = in all three signature shapes against the payload of 42.
    let needle: String = sqlx::query_scalar(
        "SELECT payload::text FROM encrypted_int4_plaintext WHERE plaintext = 42",
    )
    .fetch_one(&pool)
    .await?;
    let lit = needle.replace('\'', "''");

    // (domain, domain)
    let ids: Vec<i32> = plaintexts_matching(
        &pool,
        &format!("payload::eql_v2_int4_ord_ore = '{lit}'::jsonb::eql_v2_int4_ord_ore"),
    )
    .await?;
    assert_eq!(ids, vec![42], "(domain, domain) =");

    // (domain, jsonb)
    let ids: Vec<i32> = plaintexts_matching(
        &pool,
        &format!("payload::eql_v2_int4_ord_ore = '{lit}'::jsonb"),
    )
    .await?;
    assert_eq!(ids, vec![42], "(domain, jsonb) =");

    // (jsonb, domain) — ORM bind shape
    let ids: Vec<i32> = plaintexts_matching(
        &pool,
        &format!("'{lit}'::jsonb = payload::eql_v2_int4_ord_ore"),
    )
    .await?;
    assert_eq!(ids, vec![42], "(jsonb, domain) =");

    Ok(())
}

#[sqlx::test]
async fn encrypted_int4_inequality_against_42(pool: PgPool) -> Result<()> {
    let needle: String = sqlx::query_scalar(
        "SELECT payload::text FROM encrypted_int4_plaintext WHERE plaintext = 42",
    )
    .fetch_one(&pool)
    .await?;
    let lit = needle.replace('\'', "''");

    let ids: Vec<i32> = plaintexts_matching(
        &pool,
        &format!("payload::eql_v2_int4_ord_ore <> '{lit}'::jsonb::eql_v2_int4_ord_ore"),
    )
    .await?;
    // 14 rows, exclude 42 → 13 remaining
    let mut expected = vec![-100, -1, 1, 2, 5, 10, 17, 25, 50, 100, 250, 1000, 9999];
    expected.sort();
    assert_eq!(ids, expected, "<> against 42 should exclude only 42");

    // Reverse shape sweep
    let ids: Vec<i32> = plaintexts_matching(
        &pool,
        &format!("'{lit}'::jsonb <> payload::eql_v2_int4_ord_ore"),
    )
    .await?;
    assert_eq!(ids, expected, "reverse-shape <> against 42");

    Ok(())
}

#[sqlx::test]
async fn encrypted_int4_range_operators_match_numeric_semantics(pool: PgPool) -> Result<()> {
    // Pivot value 10. Numeric ground truth for each range operator:
    //   < 10  → { -100, -1, 1, 2, 5 }                       (5 rows)
    //   <= 10 → { -100, -1, 1, 2, 5, 10 }                   (6 rows)
    //   > 10  → { 17, 25, 42, 50, 100, 250, 1000, 9999 }    (8 rows)
    //   >= 10 → { 10, 17, 25, 42, 50, 100, 250, 1000, 9999 } (9 rows)
    let pivot: String = sqlx::query_scalar(
        "SELECT payload::text FROM encrypted_int4_plaintext WHERE plaintext = 10",
    )
    .fetch_one(&pool)
    .await?;
    let lit = pivot.replace('\'', "''");

    let cases: &[(&str, Vec<i32>)] = &[
        ("<", vec![-100, -1, 1, 2, 5]),
        ("<=", vec![-100, -1, 1, 2, 5, 10]),
        (">", vec![17, 25, 42, 50, 100, 250, 1000, 9999]),
        (">=", vec![10, 17, 25, 42, 50, 100, 250, 1000, 9999]),
    ];

    for (op, expected) in cases {
        let mut expected_sorted = expected.clone();
        expected_sorted.sort();

        // Forward shapes — value on the LHS.
        for rhs in ["'{LIT}'::jsonb::eql_v2_int4_ord_ore", "'{LIT}'::jsonb"] {
            let rhs_sql = rhs.replace("{LIT}", &lit);
            let predicate = format!("payload::eql_v2_int4_ord_ore {op} {rhs_sql}");
            let ids = plaintexts_matching(&pool, &predicate).await?;
            assert_eq!(
                ids, expected_sorted,
                "forward {op} with rhs {rhs}: predicate={predicate}"
            );
        }

        // Reverse shape — pivot on the LHS inverts the expected set.
        // Forward `value < 10` → rows where value < 10
        // Reverse `10 < value` → rows where value > 10 → "opposite" op's set
        let reverse_expected: Vec<i32> = match *op {
            "<" => vec![17, 25, 42, 50, 100, 250, 1000, 9999], // >
            "<=" => vec![10, 17, 25, 42, 50, 100, 250, 1000, 9999], // >=
            ">" => vec![-100, -1, 1, 2, 5],                    // <
            ">=" => vec![-100, -1, 1, 2, 5, 10],               // <=
            _ => unreachable!(),
        };
        let mut reverse_sorted = reverse_expected.clone();
        reverse_sorted.sort();
        let predicate = format!("'{lit}'::jsonb {op} payload::eql_v2_int4_ord_ore");
        let ids = plaintexts_matching(&pool, &predicate).await?;
        assert_eq!(
            ids, reverse_sorted,
            "reverse {op} (pivot {op} value): predicate={predicate}"
        );
    }

    Ok(())
}

#[sqlx::test]
async fn encrypted_int4_ore_ordering_matches_numeric_ordering(pool: PgPool) -> Result<()> {
    // Critical invariant: ORE bytes from Proxy must preserve numeric order.
    // Pulling all 14 rows ordered by the eql_v2_encrypted comparator must
    // yield the plaintext sequence in ascending numeric order. A bug in
    // Proxy's ORE-block encoding (sign handling, byte-order, padding)
    // would fail this without throwing.
    //
    // ORDER BY the ORE-block extractor expression directly — sorting on
    // the domain column would follow native jsonb comparison, not ORE
    // order. Using the extractor function pins the sort to ORE bytes.
    let ordered: Vec<i32> = sqlx::query_scalar(
        r#"
        SELECT plaintext
        FROM encrypted_int4_plaintext
        ORDER BY eql_v2.ore_block_u64_8_256(payload::jsonb)
        "#,
    )
    .fetch_all(&pool)
    .await?;

    let expected = vec![-100, -1, 1, 2, 5, 10, 17, 25, 42, 50, 100, 250, 1000, 9999];
    assert_eq!(
        ordered, expected,
        "ORE-block ordering must match numeric ordering of plaintext"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_int4_hmac_distinctness_sweep(pool: PgPool) -> Result<()> {
    // Pairwise: no two distinct integer plaintexts share an HMAC term.
    // 14 distinct ints → 14 distinct HMACs.
    let collisions: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_int4_plaintext a
        JOIN encrypted_int4_plaintext b ON a.id < b.id
        WHERE a.payload::eql_v2_int4_ord_ore = b.payload::eql_v2_int4_ord_ore
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(
        collisions, 0,
        "no two distinct integer plaintexts may share an HMAC term"
    );

    Ok(())
}

// Range-op index engagement is not asserted here. `_ord_ore` is seq-scan
// by design (see docs/upgrading/v2.4.md U-001 — compare_ore_block_u64_8_256
// is PL/pgSQL and does not inline). Functional-btree engagement on the
// OPE-key extractor is asserted in
// encrypted_int4_ord_ope_tests.rs::encrypted_int4_ope_idx_engages_for_range.

#[sqlx::test]
async fn encrypted_int4_hmac_btree_engages_for_eq(pool: PgPool) -> Result<()> {
    let mut tx = pool.begin().await?;

    sqlx::query(
        "CREATE INDEX encrypted_int4_plaintext_hmac_idx \
         ON encrypted_int4_plaintext \
         ((eql_v2.hmac_256(payload::jsonb)))",
    )
    .execute(&mut *tx)
    .await?;
    sqlx::query("ANALYZE encrypted_int4_plaintext")
        .execute(&mut *tx)
        .await?;
    sqlx::query("SET LOCAL enable_seqscan = off")
        .execute(&mut *tx)
        .await?;

    let needle: String = sqlx::query_scalar(
        "SELECT payload::text FROM encrypted_int4_plaintext WHERE plaintext = 42",
    )
    .fetch_one(&mut *tx)
    .await?;
    let lit = needle.replace('\'', "''");

    for op in ["=", "<>"] {
        let plan_rows: Vec<String> = sqlx::query_scalar(&format!(
            "EXPLAIN SELECT * FROM encrypted_int4_plaintext \
             WHERE payload::eql_v2_int4_ord_ore {op} '{lit}'::jsonb"
        ))
        .fetch_all(&mut *tx)
        .await?;
        let plan = plan_rows.join("\n");
        // <> typically falls back to seq scan even with seqscan=off because
        // PG considers it cost-prohibitive to use the index for inequality;
        // assert index presence only for `=`. <> correctness is covered by
        // encrypted_int4_inequality_against_42.
        if op == "=" {
            assert!(
                plan.contains("encrypted_int4_plaintext_hmac_idx"),
                "= must engage hmac functional index; plan:\n{plan}"
            );
        }
    }

    tx.commit().await?;
    Ok(())
}
