//! Fixture-driven tests for the `encrypted_text` domain operator surface.
//!
//! Unlike `encrypted_domain_types_tests.rs` (which uses minimal hand-built
//! JSONB literals to prove operator plumbing), these tests use real
//! CipherStash Proxy output from
//! `tests/sqlx/migrations/008_install_encrypted_text_fixture.sql`
//! — generated by `mise run fixture:text:generate` — to prove behavior
//! against payloads with realistic HMAC + bloom + ORE terms.
//!
//! Ground truth is the `plaintext` column on each fixture row, paired with
//! the wordlist's deterministic substring structure (e.g. `app` is a
//! substring of `apple`, `application`, `apply`).

use anyhow::Result;
use sqlx::PgPool;

#[sqlx::test]
async fn encrypted_text_equality_against_real_payload_matches_self(pool: PgPool) -> Result<()> {
    // Pick a known plaintext and look it up by encrypted_text-domain equality
    // against its own payload. The fixture has unique plaintexts so the
    // expected result is exactly that row.
    let row: (i64, String) = sqlx::query_as(
        r#"
        SELECT et.id, et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            = (SELECT payload::encrypted_text
               FROM encrypted_text_plaintext
               WHERE plaintext = 'alice')
        "#,
    )
    .fetch_one(&pool)
    .await?;

    assert_eq!(row.1, "alice", "equality should resolve to the alice row");

    // Cross-type shape: bind one side as jsonb (no explicit domain cast).
    // This exercises the (encrypted_text, jsonb) operator overload.
    let ids: Vec<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            = (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'alice')::jsonb
        "#,
    )
    .fetch_all(&pool)
    .await?;
    assert_eq!(
        ids.len(),
        1,
        "cross-type = should also match exactly one row"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_equality_distinguishes_different_plaintexts(pool: PgPool) -> Result<()> {
    // Looking up 'alice' must NOT also return 'bob'. Sanity check that the
    // operator is doing real HMAC comparison, not always-true.
    let count: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            = (SELECT payload::encrypted_text
               FROM encrypted_text_plaintext
               WHERE plaintext = 'bob')
          AND et.plaintext = 'alice'
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(count, 0, "alice row must not match bob's payload");

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_like_matches_substring_family(pool: PgPool) -> Result<()> {
    // The wordlist contains 'app', 'apple', 'application', 'apply' — all
    // share the 'app' substring. bloom_filter('apple') is built from
    // n-grams of 'apple', which is a superset of the n-grams of 'app'.
    //
    // Predicate semantics for `value ~~ needle` is
    //   bloom_filter(value) @> bloom_filter(needle)
    // — value's bloom must CONTAIN needle's bloom. So with needle='app',
    // rows whose plaintext contains 'app' as a substring should match.
    let mut matches: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            ~~ (SELECT payload::encrypted_text
                FROM encrypted_text_plaintext
                WHERE plaintext = 'app')
        ORDER BY et.plaintext
        "#,
    )
    .fetch_all(&pool)
    .await?;
    matches.sort();

    // Expected: every wordlist entry whose plaintext literally contains
    // the substring 'app'. Bloom filters are probabilistic — false
    // positives are possible — so the assertion is "at least these match"
    // and "rows clearly unrelated do not match".
    let expected_subset: Vec<&str> = vec!["app", "apple", "application", "apply"];
    for word in &expected_subset {
        assert!(
            matches.contains(&word.to_string()),
            "expected `{word}` to match bloom of 'app'; got {matches:?}"
        );
    }

    // Negative ground truth: 'bob' has no 'app' n-grams and must not match.
    assert!(
        !matches.contains(&"bob".to_string()),
        "`bob` should not match bloom of 'app'; got {matches:?}"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_like_negative_match(pool: PgPool) -> Result<()> {
    // Needle 'zebra' has no substring overlap with the rest of the wordlist
    // beyond itself. Expect exactly one row in the result set (the 'zebra'
    // row matching itself).
    let matches: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            ~~ (SELECT payload::encrypted_text
                FROM encrypted_text_plaintext
                WHERE plaintext = 'zebra')
        "#,
    )
    .fetch_all(&pool)
    .await?;
    assert!(
        matches.contains(&"zebra".to_string()),
        "zebra must match its own bloom; got {matches:?}"
    );
    // Loose upper bound: bloom filters allow false positives, so we don't
    // assert the result is exactly {zebra}. But it should be small.
    assert!(
        matches.len() <= 5,
        "zebra should not match many rows; got {matches:?}"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_like_uses_bloom_index_on_real_payloads(pool: PgPool) -> Result<()> {
    // Build a functional bloom-filter GIN on the fixture column and prove
    // the planner engages it for `~~` against a real Proxy payload. The
    // synthetic-payload version of this assertion lives in
    // encrypted_domain_types_tests.rs::encrypted_text_like_uses_bloom_index;
    // this one closes the regression gap on realistic bloom cardinality.
    let mut tx = pool.begin().await?;

    sqlx::query(
        "CREATE INDEX encrypted_text_plaintext_bloom_idx \
         ON encrypted_text_plaintext \
         USING gin ((eql_v2.bloom_filter(payload::jsonb)))",
    )
    .execute(&mut *tx)
    .await?;
    sqlx::query("ANALYZE encrypted_text_plaintext")
        .execute(&mut *tx)
        .await?;
    sqlx::query("SET LOCAL enable_seqscan = off")
        .execute(&mut *tx)
        .await?;

    // EXPLAIN with the needle bound as a literal — the planner must see the
    // inlined `bloom_filter(payload::jsonb) @> bloom_filter(<literal>)` form.
    let needle: String = sqlx::query_scalar(
        "SELECT payload::text FROM encrypted_text_plaintext WHERE plaintext = 'app'",
    )
    .fetch_one(&mut *tx)
    .await?;

    let plan_rows: Vec<String> = sqlx::query_scalar(&format!(
        "EXPLAIN SELECT * FROM encrypted_text_plaintext \
         WHERE payload::encrypted_text ~~ '{}'::jsonb",
        needle.replace('\'', "''")
    ))
    .fetch_all(&mut *tx)
    .await?;
    let plan = plan_rows.join("\n");
    assert!(
        plan.contains("encrypted_text_plaintext_bloom_idx"),
        "expected bloom functional index on fixture; plan:\n{plan}"
    );

    tx.commit().await?;
    Ok(())
}

#[sqlx::test]
async fn encrypted_text_reverse_shape_jsonb_lhs_against_fixture(pool: PgPool) -> Result<()> {
    // (jsonb, encrypted_text) reverse shape — the form ORMs hit when binding
    // parameters as jsonb. Exercises both `=` and `~~` against real payloads.
    //
    // For `=` the operator is symmetric, so binding alice on the LHS as jsonb
    // and matching against the alice row's payload::encrypted_text on the
    // RHS must still find alice (and only alice).
    let alice_only: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'alice')::jsonb
            = et.payload::encrypted_text
        "#,
    )
    .fetch_all(&pool)
    .await?;
    assert_eq!(
        alice_only,
        vec!["alice".to_string()],
        "reverse-shape = must find exactly the alice row"
    );

    // For `~~` the operator is NOT symmetric. Semantics:
    //   bloom_filter(LHS) @> bloom_filter(RHS)
    // — LHS bloom must contain RHS bloom. Reverse shape with `application`
    // as the needle on LHS finds rows whose plaintext is a substring of
    // `application`. From the wordlist that's `app` and `application` itself
    // (the other `app*` words have characters that break the substring
    // relationship: `apple` has 'e', `apply` has 'y').
    let mut substrings_of_application: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'application')::jsonb
            ~~ et.payload::encrypted_text
        ORDER BY et.plaintext
        "#,
    )
    .fetch_all(&pool)
    .await?;
    substrings_of_application.sort();

    for expected in &["app", "application"] {
        assert!(
            substrings_of_application.contains(&expected.to_string()),
            "reverse-shape ~~ must match {expected}; got {substrings_of_application:?}"
        );
    }
    // `bob` is not a substring of `application` — must not match (modulo
    // bloom false-positives which are statistically negligible for k=6,
    // m=2048 on a 9-trigram source).
    assert!(
        !substrings_of_application.contains(&"bob".to_string()),
        "reverse-shape ~~ must not match bob; got {substrings_of_application:?}"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_inequality_against_fixture(pool: PgPool) -> Result<()> {
    // `<>` against alice's payload must return every row EXCEPT alice.
    // Wordlist has 40 rows, so the expected count is 39.
    let count: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           <> (SELECT payload::encrypted_text
               FROM encrypted_text_plaintext
               WHERE plaintext = 'alice')
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(count, 39, "<> against alice should return 39 of 40 rows");

    // Also: alice must NOT appear in the <> result set (negative check).
    let neq_plaintexts: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           <> (SELECT payload::encrypted_text
               FROM encrypted_text_plaintext
               WHERE plaintext = 'alice')
        "#,
    )
    .fetch_all(&pool)
    .await?;
    assert!(
        !neq_plaintexts.contains(&"alice".to_string()),
        "alice must not appear in its own <> result; got {neq_plaintexts:?}"
    );

    // `~~*` shares its implementation with `~~` (both delegate to
    // eql_v2.encrypted_text_like). Verify as a row predicate on real data —
    // the synthetic test only resolves it as a boolean expression, not as
    // a FROM-clause filter.
    let mut ilike_matches: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           ~~* (SELECT payload::encrypted_text
                FROM encrypted_text_plaintext
                WHERE plaintext = 'app')
        ORDER BY et.plaintext
        "#,
    )
    .fetch_all(&pool)
    .await?;
    ilike_matches.sort();

    // `~~*` should match the same substring family as `~~` since the
    // wordlist is all lowercase and Proxy's match index downcases tokens.
    for expected in &["app", "apple", "application", "apply"] {
        assert!(
            ilike_matches.contains(&expected.to_string()),
            "~~* must match {expected}; got {ilike_matches:?}"
        );
    }

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_like_matches_al_family(pool: PgPool) -> Result<()> {
    // Second substring family beyond `app` to exercise tokenizer breadth
    // at zero fixture cost. Wordlist entries with the literal substring
    // `al`: alice, alien, alignment, all, alpha. Entries that share other
    // letters but NOT `al`: app/apple/application/apply (no `al` digram —
    // letters are a,p,p,l,*).
    let mut matches: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            ~~ (SELECT payload::encrypted_text
                FROM encrypted_text_plaintext
                WHERE plaintext = 'all')
        ORDER BY et.plaintext
        "#,
    )
    .fetch_all(&pool)
    .await?;
    matches.sort();

    // `all` has trigrams { all } (the only 3-char window). bloom('all')
    // is a tiny single-token filter. Every wordlist entry that includes
    // the literal `all` substring should match: that's `all` itself and
    // `alignment` (contains 'all'... wait no, alignment is a-l-i-g-n-m-e-n-t
    // — no 'all' substring). Actually only `all` contains the trigram
    // `all`. So the conservative family for needle='all' is just {all}.
    //
    // Switch needle to something with broader 'al' coverage: use the
    // shortest entry that starts with 'al' as a string: `all`. To exercise
    // the al-family we need a multi-trigram needle whose trigrams overlap
    // with multiple al-prefixed entries.
    //
    // Above query keeps `all` as the needle for the strict (`all` literal)
    // family. Then a second query uses `alpha` whose trigrams { alp, lph,
    // pha } pull in `alpha` plus any row containing `alp`/`lph`/`pha` —
    // which is just `alpha` itself in this wordlist. Use that to bound
    // false positives.
    assert!(
        matches.contains(&"all".to_string()),
        "needle 'all' must match itself; got {matches:?}"
    );
    // Negatives: app/apple/application/apply do NOT contain the trigram
    // `all`. They must not appear.
    for forbidden in &["app", "apple", "application", "apply", "bob"] {
        assert!(
            !matches.contains(&forbidden.to_string()),
            "needle 'all' must NOT match {forbidden}; got {matches:?}"
        );
    }

    // Second probe: alpha — trigrams { alp, lph, pha }. Wordlist contains
    // only `alpha` with any of these trigrams. Confirms tokenizer doesn't
    // emit spurious cross-word matches.
    let mut alpha_matches: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
            ~~ (SELECT payload::encrypted_text
                FROM encrypted_text_plaintext
                WHERE plaintext = 'alpha')
        ORDER BY et.plaintext
        "#,
    )
    .fetch_all(&pool)
    .await?;
    alpha_matches.sort();
    assert!(
        alpha_matches.contains(&"alpha".to_string()),
        "needle 'alpha' must match itself; got {alpha_matches:?}"
    );
    for forbidden in &["alice", "alien", "alignment", "all", "bob"] {
        assert!(
            !alpha_matches.contains(&forbidden.to_string()),
            "needle 'alpha' must NOT match {forbidden}; got {alpha_matches:?}"
        );
    }

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_hmac_distinctness_sweep(pool: PgPool) -> Result<()> {
    // Pairwise invariant: for every distinct (a, b) pair in the fixture,
    // a.payload::encrypted_text = b.payload::encrypted_text must be false.
    // The wordlist has unique plaintexts; the HMAC term must be unique too.
    //
    // Catches HMAC truncation, key-reuse, and any encoding bug that would
    // collapse distinct plaintexts to the same HMAC bucket.
    let collisions: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_text_plaintext a
        JOIN encrypted_text_plaintext b ON a.id < b.id
        WHERE a.payload::encrypted_text = b.payload::encrypted_text
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(
        collisions, 0,
        "no two distinct fixture plaintexts may share an HMAC term"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_eq_index_engagement_reverse_shape(pool: PgPool) -> Result<()> {
    // The synthetic suite asserts the hmac functional index engages for the
    // (encrypted_text, jsonb) cross-type shape. This closes the same
    // assertion for the (jsonb, encrypted_text) reverse shape on real
    // Proxy payloads.
    let mut tx = pool.begin().await?;

    sqlx::query(
        "CREATE INDEX encrypted_text_plaintext_hmac_idx \
         ON encrypted_text_plaintext \
         ((eql_v2.hmac_256(payload::jsonb)))",
    )
    .execute(&mut *tx)
    .await?;
    sqlx::query("ANALYZE encrypted_text_plaintext")
        .execute(&mut *tx)
        .await?;
    sqlx::query("SET LOCAL enable_seqscan = off")
        .execute(&mut *tx)
        .await?;

    let needle: String = sqlx::query_scalar(
        "SELECT payload::text FROM encrypted_text_plaintext WHERE plaintext = 'alice'",
    )
    .fetch_one(&mut *tx)
    .await?;

    let plan_rows: Vec<String> = sqlx::query_scalar(&format!(
        "EXPLAIN SELECT * FROM encrypted_text_plaintext \
         WHERE '{}'::jsonb = payload::encrypted_text",
        needle.replace('\'', "''")
    ))
    .fetch_all(&mut *tx)
    .await?;
    let plan = plan_rows.join("\n");
    assert!(
        plan.contains("encrypted_text_plaintext_hmac_idx"),
        "reverse-shape = must engage hmac functional index; plan:\n{plan}"
    );

    tx.commit().await?;
    Ok(())
}

#[sqlx::test]
async fn encrypted_text_inequality_cross_type_shapes(pool: PgPool) -> Result<()> {
    // <> in all three signature shapes against alice's payload.
    // 40 fixture rows total; <> excludes the one alice row, so each
    // shape should return 39.

    // Shape A: (domain, domain) — covered by encrypted_text_inequality_against_fixture
    // but re-asserted here for parity.
    let count_a: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           <> (SELECT payload::encrypted_text
               FROM encrypted_text_plaintext
               WHERE plaintext = 'alice')
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(count_a, 39, "(domain, domain) <> count");

    // Shape B: (domain, jsonb)
    let count_b: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           <> (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'alice')::jsonb
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(count_b, 39, "(domain, jsonb) <> count");

    // Shape C: (jsonb, domain) — the ORM-bind shape
    let count_c: i64 = sqlx::query_scalar(
        r#"
        SELECT count(*)
        FROM encrypted_text_plaintext et
        WHERE (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'alice')::jsonb
           <> et.payload::encrypted_text
        "#,
    )
    .fetch_one(&pool)
    .await?;
    assert_eq!(count_c, 39, "(jsonb, domain) <> count");

    Ok(())
}

#[sqlx::test]
async fn encrypted_text_ilike_cross_type_shapes(pool: PgPool) -> Result<()> {
    // ~~* shares its function body with ~~. The substring family for
    // needle='app' (app/apple/application/apply) must be returned in all
    // three signature shapes. This complements the same-domain ~~* coverage
    // already in encrypted_text_inequality_against_fixture.
    let expected: &[&str] = &["app", "apple", "application", "apply"];

    // Shape A: (domain, domain)
    let matches_a: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           ~~* (SELECT payload::encrypted_text
                FROM encrypted_text_plaintext
                WHERE plaintext = 'app')
        "#,
    )
    .fetch_all(&pool)
    .await?;
    for word in expected {
        assert!(
            matches_a.contains(&word.to_string()),
            "(domain, domain) ~~* must match {word}; got {matches_a:?}"
        );
    }

    // Shape B: (domain, jsonb)
    let matches_b: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE et.payload::encrypted_text
           ~~* (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'app')::jsonb
        "#,
    )
    .fetch_all(&pool)
    .await?;
    for word in expected {
        assert!(
            matches_b.contains(&word.to_string()),
            "(domain, jsonb) ~~* must match {word}; got {matches_b:?}"
        );
    }

    // Shape C: (jsonb, domain) — semantics is reverse, so the result set
    // is "rows whose plaintext is a substring of 'app'". Only 'app' itself
    // qualifies from this wordlist (everything else is longer or unrelated).
    let matches_c: Vec<String> = sqlx::query_scalar(
        r#"
        SELECT et.plaintext
        FROM encrypted_text_plaintext et
        WHERE (SELECT payload FROM encrypted_text_plaintext WHERE plaintext = 'app')::jsonb
           ~~* et.payload::encrypted_text
        "#,
    )
    .fetch_all(&pool)
    .await?;
    assert!(
        matches_c.contains(&"app".to_string()),
        "(jsonb, domain) ~~* must include 'app' (self); got {matches_c:?}"
    );
    for forbidden in &["apple", "application", "apply", "bob"] {
        assert!(
            !matches_c.contains(&forbidden.to_string()),
            "(jsonb, domain) ~~* must NOT match {forbidden}; got {matches_c:?}"
        );
    }

    Ok(())
}
