//! Fixture-driven tests for the `encrypted_jsonb` domain operator surface.
//!
//! Consumes `tests/sqlx/migrations/010_install_encrypted_jsonb_fixture.sql`,
//! generated by `mise run fixture:jsonb:generate` against real CipherStash
//! Proxy output. Each row pairs a plaintext JSON document with its
//! encrypted JSONB payload (HMAC top-level + STE-vec leaves).
//!
//! Document set (`tasks/fixtures/encrypted_jsonb_documents.json`):
//!   1. {name: alice, email: alice@example.com, score: 10}
//!   2. {name: alice, email: alice@example.com, score: 20}  — same name+email
//!   3. {name: bob,   email: bob@example.com,   score: 10}
//!   4. {name: bob,   email: bob@elsewhere.org, score: 50}
//!   5. {name: carol, email: carol@example.com}             — no score
//!   6. {name: alice}                                       — single field
//!   7. {name: alice, email: alice@example.com}             — strict subset of 1
//!   8. {name: dave,  email: dave@example.com,  score: 10}
//!
//! Operator coverage in this file: `@>`, `<@`, plus GIN index engagement.
//!
//! NOT covered here: `=`, `<>`, `->`, `->>`.
//! - `=`/`<>` need a top-level HMAC field; Proxy doesn't emit one for jsonb
//!   cast_as (the unique index lives inside each sv element's `b3` hash
//!   instead). Equality semantics for real-Proxy jsonb data require a
//!   different primitive than `hmac_256(payload->>'hm')` — deferred.
//! - `->`/`->>` need the BLAKE3-hashed selector for a path; that hash is
//!   only obtainable by encrypting the selector text through Proxy. Test
//!   support deferred until we have a runtime path for selector
//!   derivation.

use anyhow::Result;
use sqlx::PgPool;

#[sqlx::test]
async fn encrypted_jsonb_contains_finds_supersets(pool: PgPool) -> Result<()> {
    // Doc 7 (alice + email) is a STRICT SUBSET of doc 1 (alice + email + score).
    // For each row `r`, `r.payload @> doc_7.payload` is true iff r's
    // plaintext contains every selector/value pair in doc 7. The fixture
    // rows with both `name=alice` AND `email=alice@example.com` are
    // 1, 2 (different score), and 7 itself. Doc 6 (alice only, no email)
    // is excluded. Doc 5 (carol+email) is excluded.
    let mut matches: Vec<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.payload::encrypted_jsonb
           @> (SELECT payload::encrypted_jsonb
               FROM encrypted_jsonb_plaintext
               WHERE id = 7)
        ORDER BY et.id
        "#,
    )
    .fetch_all(&pool)
    .await?;
    matches.sort();
    assert_eq!(
        matches,
        vec![1, 2, 7],
        "@> doc7 (alice+email) must match rows 1, 2, 7"
    );

    // Negative: doc 6 (alice only) is NOT a superset of doc 1.
    let doc6_contains_doc1: Option<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.id = 6
          AND et.payload::encrypted_jsonb
           @> (SELECT payload::encrypted_jsonb FROM encrypted_jsonb_plaintext WHERE id = 1)
        "#,
    )
    .fetch_optional(&pool)
    .await?;
    assert_eq!(
        doc6_contains_doc1, None,
        "doc 6 (alice-only) must NOT contain doc 1 (alice+email+score)"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_jsonb_contains_cross_type_shape(pool: PgPool) -> Result<()> {
    // (domain, jsonb) shape — payload bound as jsonb literal on RHS.
    let mut matches: Vec<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.payload::encrypted_jsonb
           @> (SELECT payload FROM encrypted_jsonb_plaintext WHERE id = 7)::jsonb
        ORDER BY et.id
        "#,
    )
    .fetch_all(&pool)
    .await?;
    matches.sort();
    assert_eq!(
        matches,
        vec![1, 2, 7],
        "(domain, jsonb) @> must match the same set as (domain, domain)"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_jsonb_contained_by_returns_subsets(pool: PgPool) -> Result<()> {
    // Inverse of the @> test: every row whose plaintext is a subset of
    // doc 1 (alice + email + score). That's rows 1 (self), 6 (alice-only),
    // 7 (alice+email). Other alice docs (2 with different score) are NOT
    // subsets because score=20 ≠ score=10.
    let mut matches: Vec<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.payload::encrypted_jsonb
           <@ (SELECT payload::encrypted_jsonb
               FROM encrypted_jsonb_plaintext
               WHERE id = 1)
        ORDER BY et.id
        "#,
    )
    .fetch_all(&pool)
    .await?;
    matches.sort();
    assert_eq!(
        matches,
        vec![1, 6, 7],
        "<@ doc1 must match rows 1, 6, 7 (subsets of alice+email+score)"
    );

    // Negative: doc 2 (different score) is NOT a subset of doc 1.
    let doc2_subset_doc1: Option<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.id = 2
          AND et.payload::encrypted_jsonb
           <@ (SELECT payload::encrypted_jsonb FROM encrypted_jsonb_plaintext WHERE id = 1)
        "#,
    )
    .fetch_optional(&pool)
    .await?;
    assert_eq!(
        doc2_subset_doc1, None,
        "doc 2 (score=20) must NOT be a subset of doc 1 (score=10)"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_jsonb_containment_distinguishes_value_differences(pool: PgPool) -> Result<()> {
    // Sanity check that containment compares VALUES not just selectors.
    // Doc 3 (bob+email@example+score=10) and doc 4 (bob+email@elsewhere+score=50)
    // share the `name` and `email` selectors but differ in every value
    // except `name=bob`. Containment of doc 4 by doc 3 should be FALSE
    // (the email and score values don't match).
    let doc4_subset_doc3: Option<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.id = 4
          AND et.payload::encrypted_jsonb
           <@ (SELECT payload::encrypted_jsonb FROM encrypted_jsonb_plaintext WHERE id = 3)
        "#,
    )
    .fetch_optional(&pool)
    .await?;
    assert_eq!(
        doc4_subset_doc3, None,
        "doc 4 must NOT be a subset of doc 3 (only name matches; email/score differ)"
    );

    // But a single-field subset of doc 3 — i.e., {name: bob} — would be.
    // We don't have a {name: bob}-only row in the fixture, so verify the
    // reverse: doc 6 (alice-only) is not <@ doc 3 (because alice ≠ bob).
    let doc6_subset_doc3: Option<i64> = sqlx::query_scalar(
        r#"
        SELECT et.id
        FROM encrypted_jsonb_plaintext et
        WHERE et.id = 6
          AND et.payload::encrypted_jsonb
           <@ (SELECT payload::encrypted_jsonb FROM encrypted_jsonb_plaintext WHERE id = 3)
        "#,
    )
    .fetch_optional(&pool)
    .await?;
    assert_eq!(
        doc6_subset_doc3, None,
        "doc 6 (alice) must NOT be a subset of doc 3 (bob) — name values differ"
    );

    Ok(())
}

#[sqlx::test]
async fn encrypted_jsonb_array_gin_engages_for_contains(pool: PgPool) -> Result<()> {
    // Build a functional GIN on encrypted_jsonb_array and prove the
    // planner engages it for @>. The wrapper inlines to
    //   encrypted_jsonb_array(payload::jsonb) @> encrypted_jsonb_array(<lit>)
    // — `@>` on jsonb[] is the polymorphic anyarray operator (immutable
    // built-in) so the wrapper IS inlineable, unlike the range-op case.
    let mut tx = pool.begin().await?;

    sqlx::query(
        "CREATE INDEX encrypted_jsonb_plaintext_array_idx \
         ON encrypted_jsonb_plaintext \
         USING gin ((eql_v2.encrypted_jsonb_array(payload::jsonb)))",
    )
    .execute(&mut *tx)
    .await?;
    sqlx::query("ANALYZE encrypted_jsonb_plaintext")
        .execute(&mut *tx)
        .await?;
    sqlx::query("SET LOCAL enable_seqscan = off")
        .execute(&mut *tx)
        .await?;

    let needle: String =
        sqlx::query_scalar("SELECT payload::text FROM encrypted_jsonb_plaintext WHERE id = 7")
            .fetch_one(&mut *tx)
            .await?;
    let lit = needle.replace('\'', "''");

    let plan_rows: Vec<String> = sqlx::query_scalar(&format!(
        "EXPLAIN SELECT * FROM encrypted_jsonb_plaintext \
         WHERE payload::encrypted_jsonb @> '{lit}'::jsonb"
    ))
    .fetch_all(&mut *tx)
    .await?;
    let plan = plan_rows.join("\n");
    assert!(
        plan.contains("encrypted_jsonb_plaintext_array_idx"),
        "@> must engage encrypted_jsonb_array GIN; plan:\n{plan}"
    );

    tx.commit().await?;
    Ok(())
}
