#!/usr/bin/env bash
set -euo pipefail

# Generates an encrypted_text fixture by running plaintexts from
# encrypted_text_wordlist.txt through CipherStash Proxy and dumping the
# resulting (id, plaintext, payload jsonb) rows as a SQLx migration.
#
# Uses the existing repo Postgres on POSTGRES_PORT (mise.toml [env]) and the
# Proxy overlay brought up by `mise run proxy:up`. CipherStash workspace
# credentials are read from the shell environment (mise / direnv / profile)
# — no .env file is required.
#
# Prerequisites:
#   - mise run postgres:up       (existing Postgres container)
#   - mise run reset             (installs EQL in that Postgres)
#   - mise run proxy:up          (Proxy on localhost:6432)
#   - mise run build             (produces release/cipherstash-encrypt.sql)
#
# Output:
#   tests/sqlx/migrations/008_install_encrypted_text_fixture.sql
#
# The output is checked in; contributors without CipherStash credentials
# replay the fixture deterministically via the normal SQLx migration flow.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_SQL="$SCRIPT_DIR/encrypted_text_schema.sql"
WORDLIST="$SCRIPT_DIR/encrypted_text_wordlist.txt"
OUTPUT="$REPO_ROOT/tests/sqlx/migrations/008_install_encrypted_text_fixture.sql"

# shellcheck source=_generate_common.sh
. "$SCRIPT_DIR/_generate_common.sh"

if [ ! -f "$WORDLIST" ]; then
    echo "ERROR: $WORDLIST not found." >&2
    exit 1
fi

if [ ! -f "$SCHEMA_SQL" ]; then
    echo "ERROR: $SCHEMA_SQL not found." >&2
    exit 1
fi

echo "==> Applying fixture schema (drops + recreates bench_text)"
psql "$PG_URL" -v ON_ERROR_STOP=1 -f "$SCHEMA_SQL"

restart_proxy_and_wait

echo "==> Inserting plaintexts through Proxy (this encrypts encrypted_text column)"
# Build a VALUES list from the wordlist. Both columns receive the same word;
# Proxy encrypts only the column registered in add_search_config
# (encrypted_text). The plaintext column passes through unchanged.
VALUES_SQL=""
ROW_COUNT=0
while IFS= read -r word; do
    [ -z "$word" ] && continue
    if [ -n "$VALUES_SQL" ]; then
        VALUES_SQL="$VALUES_SQL,"
    fi
    # Escape single quotes for SQL string literal.
    escaped="${word//\'/\'\'}"
    VALUES_SQL="$VALUES_SQL ('$escaped', '$escaped')"
    ROW_COUNT=$((ROW_COUNT + 1))
done < "$WORDLIST"

psql "$PROXY_URL" -v ON_ERROR_STOP=1 -c "
INSERT INTO bench_text (plaintext, encrypted_text) VALUES $VALUES_SQL;
"

echo "==> Dumping $ROW_COUNT rows to $OUTPUT"
cat > "$OUTPUT" <<HEADER
-- AUTO-GENERATED by tasks/fixtures/generate_encrypted_text.sh
-- DO NOT EDIT BY HAND. Re-run the generator to refresh.
--
-- Source: tasks/fixtures/encrypted_text_wordlist.txt
-- Produced via CipherStash Proxy (HMAC + bloom + ORE terms).
-- Used by encrypted_text domain SQLx fixture tests.

DROP TABLE IF EXISTS encrypted_text_plaintext;

CREATE TABLE encrypted_text_plaintext (
    id BIGINT PRIMARY KEY,
    plaintext TEXT NOT NULL,
    payload JSONB NOT NULL
);

HEADER

dump_fixture_table \
    "bench_text" \
    "encrypted_text_plaintext" \
    "id, plaintext, (encrypted_text).data::text" \
    "%L, %L, %L::jsonb" \
    "(id, plaintext, payload)" \
    "$OUTPUT"

echo "==> Done. Wrote $ROW_COUNT rows to $OUTPUT"
