#!/usr/bin/env bash
set -euo pipefail

# Generates an encrypted_int4 fixture by running an integer value set
# through CipherStash Proxy and dumping the resulting (id, plaintext,
# payload jsonb) rows as a SQLx migration.
#
# Prerequisites:
#   - mise run postgres:up
#   - EQL installed (e.g. via mise run reset + psql -f release/cipherstash-encrypt.sql)
#   - mise run proxy:up    (Proxy on localhost:6432)
#   - mise run build       (produces release/cipherstash-encrypt.sql)
#
# Output:
#   tests/sqlx/migrations/009_install_encrypted_int4_fixture.sql

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_SQL="$SCRIPT_DIR/encrypted_int4_schema.sql"
OUTPUT="$REPO_ROOT/tests/sqlx/migrations/009_install_encrypted_int4_fixture.sql"

# shellcheck source=_generate_common.sh
. "$SCRIPT_DIR/_generate_common.sh"

if [ ! -f "$SCHEMA_SQL" ]; then
    echo "ERROR: $SCHEMA_SQL not found." >&2
    exit 1
fi

# 14 values: includes negatives (boundary), small/medium/large/extreme.
# Chosen so range pivots produce distinct cardinalities — see plan in
# docs/superpowers/plans/.
VALUES=(-100 -1 1 2 5 10 17 25 42 50 100 250 1000 9999)
ROW_COUNT=${#VALUES[@]}

echo "==> Applying fixture schema (drops + recreates bench_int4)"
psql "$PG_URL" -v ON_ERROR_STOP=1 -f "$SCHEMA_SQL"

restart_proxy_and_wait

echo "==> Inserting $ROW_COUNT integers through Proxy (encrypts encrypted_int4)"
# Proxy's eql-mapper cannot unify negative integer literals (parsed as
# UnaryOp(Minus, ...)) with the EQL int column when sent via the simple
# query protocol. Send each value over the extended protocol via psql's
# \bind meta-command so the parameter type is communicated as a binary
# int4 instead of being inferred from SQL surface syntax.
INSERT_SQL=$(mktemp)
trap 'rm -f "$INSERT_SQL"' EXIT
for v in "${VALUES[@]}"; do
    # Use literal $1/$2 as bind placeholders; \bind supplies their values.
    # \g executes the buffered statement; \bind discards bindings after \g.
    printf 'INSERT INTO bench_int4 (plaintext, encrypted_int4) VALUES ($1, $2) \\bind %s %s \\g\n' "$v" "$v" >> "$INSERT_SQL"
done
psql "$PROXY_URL" -v ON_ERROR_STOP=1 -f "$INSERT_SQL" >/dev/null

echo "==> Dumping $ROW_COUNT rows to $OUTPUT"
cat > "$OUTPUT" <<'HEADER'
-- AUTO-GENERATED by tasks/fixtures/generate_encrypted_int4.sh
-- DO NOT EDIT BY HAND. Re-run the generator to refresh.
--
-- Source: 14-value integer set defined inline in the generator.
-- Produced via CipherStash Proxy (HMAC + ORE-block terms).
-- Each row carries `c`, `hm`, `ob`. The ordered variants
-- (eql_v2_int4_ord_ore, eql_v2_int4_ord) read `ob` only; the `hm`
-- term is retained because the same payload feeds eql_v2_int4_eq.
-- Used by the encrypted_int4 variant-family SQLx test suites.

DROP TABLE IF EXISTS encrypted_int4_plaintext;

CREATE TABLE encrypted_int4_plaintext (
    id BIGINT PRIMARY KEY,
    plaintext INTEGER NOT NULL,
    payload JSONB NOT NULL
);

HEADER

dump_fixture_table \
    "bench_int4" \
    "encrypted_int4_plaintext" \
    "id, plaintext, (encrypted_int4).data::text" \
    "%L, %L, %L::jsonb" \
    "(id, plaintext, payload)" \
    "$OUTPUT"

echo "==> Done. Wrote $ROW_COUNT rows to $OUTPUT"
