#!/usr/bin/env bash
set -euo pipefail

# Generates an encrypted_jsonb fixture by running JSON documents through
# CipherStash Proxy and dumping (id, plaintext, payload jsonb) rows as a
# SQLx migration.
#
# Prerequisites:
#   - mise run postgres:up
#   - EQL installed (e.g. via mise run reset + psql -f release/cipherstash-encrypt.sql)
#   - mise run proxy:up    (Proxy on localhost:6432)
#   - mise run build       (produces release/cipherstash-encrypt.sql)
#
# Output:
#   tests/sqlx/migrations/010_install_encrypted_jsonb_fixture.sql

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_SQL="$SCRIPT_DIR/encrypted_jsonb_schema.sql"
DOCS_JSON="$SCRIPT_DIR/encrypted_jsonb_documents.json"
OUTPUT="$REPO_ROOT/tests/sqlx/migrations/010_install_encrypted_jsonb_fixture.sql"

# shellcheck source=_generate_common.sh
. "$SCRIPT_DIR/_generate_common.sh"

if [ ! -f "$DOCS_JSON" ]; then
    echo "ERROR: $DOCS_JSON not found." >&2
    exit 1
fi

if [ ! -f "$SCHEMA_SQL" ]; then
    echo "ERROR: $SCHEMA_SQL not found." >&2
    exit 1
fi

echo "==> Applying fixture schema (drops + recreates bench_jsonb)"
psql "$PG_URL" -v ON_ERROR_STOP=1 -f "$SCHEMA_SQL"

restart_proxy_and_wait

echo "==> Inserting JSON documents through Proxy (encrypts encrypted_jsonb)"
# Stream each top-level array element through psql's \bind to avoid
# multi-row VALUES inference issues. Each doc is passed as a jsonb
# parameter; Proxy sees the JSON value, recognizes it via the encrypt
# config, and rewrites the insert.
INSERT_SQL=$(mktemp)
trap 'rm -f "$INSERT_SQL"' EXIT
ROW_COUNT=0
# jq -c emits one compact JSON object per line.
while IFS= read -r doc; do
    [ -z "$doc" ] && continue
    # SQL-escape: single quotes inside the JSON object need doubling.
    escaped="${doc//\'/\'\'}"
    printf 'INSERT INTO bench_jsonb (plaintext, encrypted_jsonb) VALUES ($1, $2) \\bind %s %s \\g\n' \
        "'$escaped'" "'$escaped'" >> "$INSERT_SQL"
    ROW_COUNT=$((ROW_COUNT + 1))
done < <(jq -c '.[]' "$DOCS_JSON")

psql "$PROXY_URL" -v ON_ERROR_STOP=1 -f "$INSERT_SQL" >/dev/null

echo "==> Dumping $ROW_COUNT rows to $OUTPUT"
cat > "$OUTPUT" <<HEADER
-- AUTO-GENERATED by tasks/fixtures/generate_encrypted_jsonb.sh
-- DO NOT EDIT BY HAND. Re-run the generator to refresh.
--
-- Source: tasks/fixtures/encrypted_jsonb_documents.json
-- Produced via CipherStash Proxy (HMAC + STE-vec terms).
-- Used by encrypted_jsonb domain SQLx fixture tests.

DROP TABLE IF EXISTS encrypted_jsonb_plaintext;

CREATE TABLE encrypted_jsonb_plaintext (
    id BIGINT PRIMARY KEY,
    plaintext JSONB NOT NULL,
    payload JSONB NOT NULL
);

HEADER

dump_fixture_table \
    "bench_jsonb" \
    "encrypted_jsonb_plaintext" \
    "id, plaintext::text, (encrypted_jsonb).data::text" \
    "%L, %L::jsonb, %L::jsonb" \
    "(id, plaintext, payload)" \
    "$OUTPUT"

echo "==> Done. Wrote $ROW_COUNT rows to $OUTPUT"
