//! Proc-macros that expand the scalar-harness list into per-type SQLx matrix
//! wiring.
//!
//! Each entry is `token => rust_type`, where `token` is the Postgres type token
//! and fixture/domain suffix, and `rust_type` is the Rust plaintext type:
//!
//! ```ignore
//! eql_tests::scalar_harness! {
//!     int4 => i32,
//!     int2 => i16,
//!     int8 => i64,
//! }
//! ```
//!
//! The catalog value const is derived by
//! upper-casing the token and appending `_VALUES` (`int4` -> `INT4_VALUES`),
//! matching `eql_scalars::INT4_VALUES`.
//!
//! The emitters are split into thin `#[proc_macro]` shims and pure
//! `proc_macro2::TokenStream` core functions (`*_tokens`) for unit tests.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{Ident, Token, Type};

/// One `token => rust_type` entry from the harness list.
struct ScalarEntry {
    /// The Postgres type token (`int4`), also the fixture/domain name suffix
    /// and the `suite` ident in the matrix invocation.
    token: Ident,
    /// The Rust plaintext type (`i32`).
    rust_type: Type,
}

impl Parse for ScalarEntry {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let token: Ident = input.parse()?;
        input.parse::<Token![=>]>()?;
        let rust_type: Type = input.parse()?;
        Ok(ScalarEntry { token, rust_type })
    }
}

/// The whole comma-separated list, with optional trailing comma.
struct ScalarList {
    entries: Vec<ScalarEntry>,
}

impl Parse for ScalarList {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let punctuated = Punctuated::<ScalarEntry, Token![,]>::parse_terminated(input)?;
        Ok(ScalarList {
            entries: punctuated.into_iter().collect(),
        })
    }
}

/// `int4` -> `INT4_VALUES` — the catalog value const for a token. Mirrors the
/// `int_values!(INT4_VALUES, ...)` naming in `eql_scalars`.
fn values_const_ident(token: &Ident) -> Ident {
    format_ident!("{}_VALUES", token.to_string().to_uppercase())
}

// ---------------------------------------------------------------------------
// Core token generators (pure, unit-testable).
// ---------------------------------------------------------------------------

/// Emit one `impl ScalarType for <rust_type>` per entry. See
/// [`emit_scalar_type_impls`].
fn scalar_type_impls_tokens(list: &ScalarList) -> TokenStream2 {
    let impls = list.entries.iter().map(|e| {
        let token_str = e.token.to_string();
        let rust_type = &e.rust_type;
        let values = values_const_ident(&e.token);
        quote! {
            impl ScalarType for #rust_type {
                const PG_TYPE: &'static str = #token_str;
                /// Materialised from the matching `eql-scalars::CATALOG` row.
                const FIXTURE_VALUES: &'static [#rust_type] = ::eql_scalars::#values;
            }
        }
    });
    quote! { #(#impls)* }
}

/// Emit one `pub mod eql_v2_<token> { ... }` per entry. See
/// [`emit_scalar_fixture_modules`].
fn scalar_fixture_modules_tokens(list: &ScalarList) -> TokenStream2 {
    let mods = list.entries.iter().map(|e| {
        let token_str = e.token.to_string();
        let rust_type = &e.rust_type;
        let values = values_const_ident(&e.token);
        let mod_ident = format_ident!("eql_v2_{}", e.token);
        let fixture_name = format!("eql_v2_{}", token_str);
        quote! {
            #[doc = concat!("`eql_v2_", #token_str, "` scalar fixture — generated by `scalar_harness!`.")]
            pub mod #mod_ident {
                use ::eql_scalars::#values as VALUES;
                // Modules are emitted inside `eql-tests`, where `crate::scalar_fixture!` resolves.
                crate::scalar_fixture!(#fixture_name, #rust_type, VALUES);
            }
        }
    });
    quote! { #(#mods)* }
}

/// Emit the `generate_for_token` dispatch fn. See [`emit_fixture_dispatch`].
fn fixture_dispatch_tokens(list: &ScalarList) -> TokenStream2 {
    let arms = list.entries.iter().map(|e| {
        let token_str = e.token.to_string();
        let mod_ident = format_ident!("eql_v2_{}", e.token);
        quote! {
            #token_str => ::eql_tests::fixtures::#mod_ident::spec().run().await,
        }
    });
    quote! {
        /// Run the fixture generator for a catalog token from the scalar harness list.
        async fn generate_for_token(token: &str) -> anyhow::Result<()> {
            match token {
                #(#arms)*
                other => anyhow::bail!(
                    "no fixture generator wired for catalog token '{other}'. \
                     Add it to the scalar_harness! list (tests/sqlx/src/scalar_harness.rs). \
                     See the encrypted-domain spec §3."
                ),
            }
        }
    }
}

/// Emit one `pub mod <token> { ordered_numeric_matrix! { ... } }` per entry.
/// See [`emit_scalar_matrix_suites`].
fn scalar_matrix_suites_tokens(list: &ScalarList) -> TokenStream2 {
    let mods = list.entries.iter().map(|e| {
        let token = &e.token;
        let token_str = e.token.to_string();
        let rust_type = &e.rust_type;
        let eql_type = format!("eql_v2_{}", token_str);
        quote! {
            #[doc = concat!("`eql_v2_", #token_str, "` matrix suite — generated by `scalar_harness!`.")]
            pub mod #token {
                ::eql_tests::ordered_numeric_matrix! {
                    suite = #token,
                    scalar = #rust_type,
                    eql_type = #eql_type,
                }
            }
        }
    });
    quote! { #(#mods)* }
}

// ---------------------------------------------------------------------------
// Proc-macro shims.
// ---------------------------------------------------------------------------

/// Emit one `impl ScalarType for <rust_type>` per entry.
///
/// Invoked via `scalar_harness!` inside `tests/sqlx/src/scalar_domains.rs`.
/// `PG_TYPE` is the token string; `FIXTURE_VALUES` is
/// `eql_scalars::<TOKEN_UPPER>_VALUES`.
#[proc_macro]
pub fn emit_scalar_type_impls(input: TokenStream) -> TokenStream {
    let list = syn::parse_macro_input!(input as ScalarList);
    scalar_type_impls_tokens(&list).into()
}

/// Emit one `pub mod eql_v2_<token> { ... }` per entry.
///
/// Invoked via `scalar_harness!` inside `tests/sqlx/src/fixtures/mod.rs`, where
/// the modules land at `crate::fixtures::eql_v2_<token>`.
#[proc_macro]
pub fn emit_scalar_fixture_modules(input: TokenStream) -> TokenStream {
    let list = syn::parse_macro_input!(input as ScalarList);
    scalar_fixture_modules_tokens(&list).into()
}

/// Emit the `generate_for_token` dispatch.
///
/// Invoked via `scalar_harness!` inside `tests/generate_all_fixtures.rs`.
/// Emits an async `generate_for_token` with one match arm per entry plus a
/// catch-all.
#[proc_macro]
pub fn emit_fixture_dispatch(input: TokenStream) -> TokenStream {
    let list = syn::parse_macro_input!(input as ScalarList);
    fixture_dispatch_tokens(&list).into()
}

/// Emit one `pub mod <token> { ordered_numeric_matrix! { ... } }` per entry.
///
/// Invoked via `scalar_harness!` inside
/// `tests/sqlx/tests/encrypted_domain/scalars/mod.rs`. This emitter is separate
/// because integration-test suites must be emitted in the integration-test
/// target; it preserves the generated `scalars::<token>::matrix_*` test names.
#[proc_macro]
pub fn emit_scalar_matrix_suites(input: TokenStream) -> TokenStream {
    let list = syn::parse_macro_input!(input as ScalarList);
    scalar_matrix_suites_tokens(&list).into()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> ScalarList {
        syn::parse_str::<ScalarList>("int4 => i32, int8 => i64,").unwrap()
    }

    /// The token-stream comparison is on the normalized `to_string()` form so
    /// whitespace/formatting differences don't make the assertions brittle.
    fn norm(ts: &TokenStream2) -> String {
        ts.to_string()
    }

    #[test]
    fn values_const_name_is_uppercased_with_suffix() {
        let token: Ident = syn::parse_str("int8").unwrap();
        assert_eq!(values_const_ident(&token).to_string(), "INT8_VALUES");
    }

    #[test]
    fn scalar_type_impls_emit_pg_type_and_fixture_values() {
        let out = norm(&scalar_type_impls_tokens(&sample()));
        // One impl per entry, with the right PG_TYPE string and catalog const.
        assert!(out.contains("impl ScalarType for i32"));
        assert!(out.contains("impl ScalarType for i64"));
        assert!(out.contains(r#"const PG_TYPE : & 'static str = "int4""#));
        assert!(out.contains(r#"const PG_TYPE : & 'static str = "int8""#));
        assert!(out.contains(":: eql_scalars :: INT4_VALUES"));
        assert!(out.contains(":: eql_scalars :: INT8_VALUES"));
    }

    #[test]
    fn fixture_modules_emit_named_mods_with_scalar_fixture() {
        let out = norm(&scalar_fixture_modules_tokens(&sample()));
        assert!(out.contains("pub mod eql_v2_int4"));
        assert!(out.contains("pub mod eql_v2_int8"));
        assert!(out.contains("crate :: scalar_fixture !"));
        assert!(out.contains(r#""eql_v2_int4""#));
        assert!(out.contains(":: eql_scalars :: INT4_VALUES as VALUES"));
    }

    #[test]
    fn fixture_dispatch_emits_one_arm_per_token_and_a_catch_all() {
        let out = norm(&fixture_dispatch_tokens(&sample()));
        assert!(out.contains("async fn generate_for_token"));
        assert!(out.contains(r#""int4" =>"#));
        assert!(out.contains(r#""int8" =>"#));
        assert!(out.contains(":: eql_tests :: fixtures :: eql_v2_int4 :: spec"));
        // Loud catch-all preserved.
        assert!(out.contains("other =>"));
        assert!(out.contains("no fixture generator wired"));
    }

    #[test]
    fn matrix_suites_emit_mods_with_unchanged_suite_and_eql_type() {
        let out = norm(&scalar_matrix_suites_tokens(&sample()));
        assert!(out.contains("pub mod int4"));
        assert!(out.contains("pub mod int8"));
        assert!(out.contains(":: eql_tests :: ordered_numeric_matrix !"));
        // suite/scalar/eql_type preserve the generated test names and snapshot.
        assert!(out.contains("suite = int4"));
        assert!(out.contains("scalar = i32"));
        assert!(out.contains(r#"eql_type = "eql_v2_int4""#));
        assert!(out.contains("suite = int8"));
        assert!(out.contains("scalar = i64"));
        assert!(out.contains(r#"eql_type = "eql_v2_int8""#));
    }
}
