//! AUTO-GENERATED headers, schema constants, and SQL-string escaping.

/// SQL generated-file marker — the header's first line, with no trailing
/// newline. The SQL templates emit it (followed by a newline) as line 1, and the
/// writer uses it to recognise files it owns (overwrite/clean safety). Tests that
/// synthesise file bodies append `\n` to form the full header line.
pub(crate) const AUTO_GENERATED_MARKER: &str = "-- AUTOMATICALLY GENERATED FILE.";

/// Rust generated-file marker — the `// @generated` header's first line, with
/// no trailing newline. `bindings::format_rs` prepends it (followed by a
/// newline) as line 1 and then runs `rustfmt` over the whole file (rustfmt
/// preserves a leading line comment), and the writer (`GeneratedKind::Rust`)
/// uses it to recognise files it owns.
pub(crate) const RUST_GENERATED_MARKER: &str =
    "// @generated by eql-codegen from the eql-domains catalog — do not edit";

/// The public `eql_v3` API surface: the encrypted-domain families, query
/// operators, index extractors, and aggregates. Internal implementation
/// detail (SEM index-term types, operator-backing wrappers/blockers/state
/// functions) lives in `INTERNAL_SCHEMA` instead, so `eql_v3` stays a clean
/// public surface with no `eql_v2` dependency.
pub(crate) const SCHEMA: &str = "eql_v3";

/// The schema housing every INTERNAL eql_v3 object: the SEM index-term types
/// (`hmac_256`, `bloom_filter`, `ore_block_256(_term)`, `ore_cllw`) and their
/// support functions, plus the generated scalar operator-backing wrappers,
/// unsupported-operator blockers, and aggregate state functions. Split out of
/// `SCHEMA` so `eql_v3` is a clean public API (domains, extractors, operators,
/// aggregates) and implementation detail lives in `eql_v3_internal` — keeping
/// internal index-term TYPES out of the Supabase type picker.
pub(crate) const INTERNAL_SCHEMA: &str = "eql_v3_internal";

/// Always-present payload keys checked for presence in every domain CHECK.
/// Term-specific keys are appended after these by `context::domain_block`.
/// Defined in the catalog (`eql_domains::ENVELOPE_KEYS`) so the CHECKs and
/// the `eql-bindings` payload structs share one envelope definition.
pub(crate) const ENVELOPE_KEYS: &[&str] = eql_domains::ENVELOPE_KEYS;

/// Escape a string for use inside a single-quoted SQL literal by doubling
/// embedded single quotes.
pub(crate) fn sql_str(s: &str) -> String {
    s.replace('\'', "''")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sql_marker_is_grep_compatible_single_line() {
        // The `^-- AUTOMATICALLY GENERATED FILE` marker is what
        // tasks/docs/validate/{coverage,required-tags}.sh grep on to skip
        // generated SQL — keep this assertion and that grep in lockstep. The
        // marker is a single line with no embedded newline (tests append `\n`).
        assert_eq!(AUTO_GENERATED_MARKER, "-- AUTOMATICALLY GENERATED FILE.");
        assert!(!AUTO_GENERATED_MARKER.contains('\n'));
    }

    #[test]
    fn sql_str_doubles_single_quotes() {
        assert_eq!(sql_str("o'brien"), "o''brien");
        assert_eq!(sql_str("a'b'c"), "a''b''c");
        assert_eq!(sql_str("int4_eq"), "int4_eq");
        assert_eq!(sql_str("<="), "<=");
    }
}
