#!/usr/bin/env bash
#MISE description="Generate API documentation (with Doxygen)"
# Depends on `build` because the encrypted-domain SQL under
# src/encrypted_domain/<T>/ is gitignored and regenerated by the build (see
# tasks/build.sh and tasks/codegen/). Doxygen reads INPUT=src/ per Doxyfile,
# so without this dep a fresh checkout produces incomplete API docs that omit
# the int4 / future-scalar encrypted-domain types.
#MISE depends=["build"]

set -e

if ! which -s doxygen; then
  echo "error: doxygen not installed"
  exit 2
fi

echo "Generating API documentation..."
echo
doxygen Doxyfile
echo "✓ Documentation generated:"
echo "  - XML (primary): docs/api/xml/"
echo "  - HTML (preview): docs/api/html/index.html"
echo ""
