#!/usr/bin/env bash
#MISE description="Validate SQL documentation"
# Depends on `build` because the encrypted-domain SQL under
# src/encrypted_domain/<T>/ is gitignored and regenerated by the build (see
# tasks/build.sh and tasks/codegen/). Without this dep, doxygen-coverage /
# required-tags / documented-sql validation runs against a partial source
# tree on a fresh checkout and silently skips generated files.
#MISE depends=["build"]

set -e

echo
echo "Checking documentation coverage..."
mise run --output prefix docs:validate:coverage

echo
echo "Validating required tags..."
mise run --output prefix docs:validate:required-tags

echo
echo "Validating SQL in documentation..."
mise run --output prefix docs:validate:documented-sql
