services:
  postgres:
    container_name: gotest_pg
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - ${PGPORT:-5432}:5432
    networks:
      - my-network
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
  proxy:
    container_name: gotest_proxy
    image: cipherstash/cipherstash-proxy:cipherstash-proxy-v0.1.0
    depends_on:
      - postgres
    ports:
      - ${CS_PORT:-6432}:${CS_PORT:-6432}
    environment:
      CS_WORKSPACE_ID: $CS_WORKSPACE_ID
      CS_CLIENT_ACCESS_KEY: $CS_CLIENT_ACCESS_KEY
      CS_ENCRYPTION__CLIENT_ID: $CS_ENCRYPTION__CLIENT_ID
      CS_ENCRYPTION__CLIENT_KEY: $CS_ENCRYPTION__CLIENT_KEY
      CS_TEST_ON_CHECKOUT: "true"
      CS_AUDIT__ENABLED: "false"
      CS_DATABASE__PORT: 5432
      CS_DATABASE__USERNAME: postgres
      CS_DATABASE__PASSWORD: postgres
      CS_DATABASE__NAME: gotest
      CS_DATABASE__HOST: postgres
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
